
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 08 03:27:24 BRT 2015
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int POINT = 4;
  public static final int MULT = 6;
  public static final int IMPORT = 5;
  public static final int error = 1;
  public static final int IDENTIFIER = 7;
  public static final int SEMI = 2;
  public static final int PACKAGE = 3;
  public static final int EOF = 0;
}

