
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 09 14:45:24 BRT 2015
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int IMPORT = 6;
  public static final int CLASS = 8;
  public static final int RBRACE = 22;
  public static final int PRIVATE = 13;
  public static final int SEMI = 2;
  public static final int NATIVE = 17;
  public static final int IDENTIFIER = 23;
  public static final int POINT = 4;
  public static final int LBRACE = 21;
  public static final int PUBLIC = 11;
  public static final int VOLATILE = 20;
  public static final int STATIC = 14;
  public static final int IMPLEMENTS = 10;
  public static final int COMMA = 5;
  public static final int PROTECTED = 12;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int TRANSIENT = 19;
  public static final int FINAL = 16;
  public static final int error = 1;
  public static final int ABSTRACT = 15;
  public static final int SYNCHRONIZED = 18;
  public static final int PACKAGE = 3;
  public static final int EXTENDS = 9;
}

