
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 10 21:21:39 BRT 2015
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int DIVEQ = 37;
  public static final int PLUSPLUS = 32;
  public static final int SHORT = 57;
  public static final int GTEQ = 40;
  public static final int MULT = 7;
  public static final int CHAR = 56;
  public static final int LTEQ = 41;
  public static final int MODEQ = 27;
  public static final int XOR = 63;
  public static final int DOUBLE = 61;
  public static final int SEMI = 2;
  public static final int PRIVATE = 13;
  public static final int INT = 58;
  public static final int MINUS = 29;
  public static final int STATIC = 14;
  public static final int OROR = 51;
  public static final int NOT = 28;
  public static final int LT = 39;
  public static final int OR = 50;
  public static final int COMMA = 5;
  public static final int CLASS = 8;
  public static final int DIV = 36;
  public static final int PLUSEQ = 33;
  public static final int MINUSEQ = 34;
  public static final int PLUS = 31;
  public static final int AMPERSAND = 48;
  public static final int XOREQ = 62;
  public static final int BOOLEAN = 54;
  public static final int ABSTRACT = 15;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 30;
  public static final int TRUE = 44;
  public static final int error = 1;
  public static final int TRANSIENT = 19;
  public static final int OREQ = 52;
  public static final int EQEQ = 42;
  public static final int MULTEQ = 35;
  public static final int MOD = 26;
  public static final int EQ = 25;
  public static final int BYTE = 55;
  public static final int LBRACK = 23;
  public static final int IMPORT = 6;
  public static final int COLON = 47;
  public static final int LBRACE = 21;
  public static final int NATIVE = 17;
  public static final int PROTECTED = 12;
  public static final int POINT = 4;
  public static final int RBRACK = 24;
  public static final int PACKAGE = 3;
  public static final int FINAL = 16;
  public static final int FLOAT = 59;
  public static final int PUBLIC = 11;
  public static final int RBRACE = 22;
  public static final int EXTENDS = 9;
  public static final int LONG = 60;
  public static final int QUESTION = 46;
  public static final int VOLATILE = 20;
  public static final int AMPERSANDEQ = 49;
  public static final int OROREQ = 53;
  public static final int SYNCHRONIZED = 18;
  public static final int FALSE = 45;
  public static final int GT = 38;
  public static final int IMPLEMENTS = 10;
  public static final int NOTEQ = 43;
  public static final int IDENTIFIER = 64;
}

