
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int POINT = 4;
  public static final int MULT = 6;
  public static final int IMPORT = 5;
  public static final int error = 1;
  public static final int IDENTIFIER = 7;
  public static final int SEMI = 2;
  public static final int PACKAGE = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PACKAGE",
  "POINT",
  "IMPORT",
  "MULT",
  "IDENTIFIER"
  };
}

